ALTER TABLE `catalog_items`
  MODIFY `kind` ENUM(
    'REQUEST_TYPE',
    'IDENTIFICATION_TYPE',
    'DOCUMENT_TYPE',
    'ACCESS_POINT',
    'SECURITY_ZONE',
    'ACCESS_AREA',
    'REJECTION_REASON',
    'GENDER',
    'MARITAL_STATUS',
    'BLOOD_TYPE',
    'NATIONALITY'
  ) NOT NULL;
