import type { Catalogs } from '@/lib/types';

export const mockCatalogs: Catalogs = {
  requestTypes: [
    { id: 'rt_carne', label: 'Carné permanente', code: 'CARNE_PERMANENTE', description: 'Carné permanente para personal', active: true },
    { id: 'rt_persona', label: 'Permiso temporal para persona', code: 'PERMISO_PERSONA', description: 'Acceso temporal de persona', active: true },
    { id: 'rt_vehiculo', label: 'Permiso temporal para vehículo', code: 'PERMISO_VEHICULO', description: 'Acceso temporal de vehículo', active: true },
    { id: 'rt_herramienta', label: 'Permiso temporal para herramienta o equipo', code: 'PERMISO_HERRAMIENTA', description: 'Acceso temporal de herramienta/equipo', active: true },
  ],
  idTypes: [
    { id: 'it_cedula', label: 'Cédula', code: 'CEDULA', active: true },
    { id: 'it_pasaporte', label: 'Pasaporte', code: 'PASAPORTE', active: true },
    { id: 'it_ruc', label: 'RUC', code: 'RUC', active: true },
    { id: 'it_carnet', label: 'Carnet de extranjería', code: 'CARNET_EXTRANJERIA', active: true },
  ],
  documentTypes: [
    { id: 'dt_cedula', label: 'Cédula o pasaporte', code: 'CEDULA', active: true },
    { id: 'dt_foto', label: 'Fotografía', code: 'FOTO', active: true },
    { id: 'dt_carta', label: 'Carta de trabajo', code: 'CARTA_TRABAJO', active: true },
    { id: 'dt_paz_salvo', label: 'Paz y salvo', code: 'PAZ_SALVO', active: true },
    { id: 'dt_cert', label: 'Certificación de la empresa', code: 'CERT_EMPRESA', active: true },
    { id: 'dt_aut', label: 'Documento de autorización', code: 'AUTORIZACION', active: true },
    { id: 'dt_veh', label: 'Documento del vehículo', code: 'DOC_VEHICULO', active: true },
    { id: 'dt_listado', label: 'Listado de herramientas o equipos', code: 'LISTADO_EQUIPOS', active: true },
  ],
  accessPoints: [
    { id: 'ap_emp', label: 'Puerta de empleados T1–T2', code: 'EMP_T1T2', active: true },
    { id: 'ap_food', label: 'Food Court', code: 'FOOD_COURT', active: true },
    { id: 'ap_p1', label: 'Portón No. 1', code: 'PORTON_1', active: true },
    { id: 'ap_p2', label: 'Portón No. 2', code: 'PORTON_2', active: true },
    { id: 'ap_p3', label: 'Portón No. 3', code: 'PORTON_3', active: true },
    { id: 'ap_p8', label: 'Portón No. 8', code: 'PORTON_8', active: true },
    { id: 'ap_p9', label: 'Portón No. 9', code: 'PORTON_9', active: true },
    { id: 'ap_p10', label: 'Portón No. 10', code: 'PORTON_10', active: true },
    { id: 'ap_p11', label: 'Portón No. 11', code: 'PORTON_11', active: true },
    { id: 'ap_p12', label: 'Portón No. 12', code: 'PORTON_12', active: true },
    { id: 'ap_p13', label: 'Portón No. 13', code: 'PORTON_13', active: true },
    { id: 'ap_p14', label: 'Portón No. 14', code: 'PORTON_14', active: true },
    { id: 'ap_p15', label: 'Portón No. 15', code: 'PORTON_15', active: true },
    { id: 'ap_carga', label: 'Edificio de carga', code: 'EDIF_CARGA', active: true },
  ],
  securityZones: [
    { id: 'sz_roja', label: 'Roja', code: 'ROJA', description: 'Zona de seguridad crítica', active: true },
    { id: 'sz_naranja', label: 'Naranja', code: 'NARANJA', active: true },
    { id: 'sz_azul', label: 'Azul', code: 'AZUL', active: true },
    { id: 'sz_amarilla', label: 'Amarilla', code: 'AMARILLA', active: true },
    { id: 'sz_verde', label: 'Verde', code: 'VERDE', active: true },
    { id: 'sz_blanca', label: 'Blanca', code: 'BLANCA', active: true },
    { id: 'sz_celeste', label: 'Celeste', code: 'CELESTE', active: true },
  ],
  accessAreas: [
    { id: 'aa_roja_a', label: 'Plataforma', code: 'ROJA-A', active: true },
    { id: 'aa_roja_b', label: 'Calle de rodaje', code: 'ROJA-B', active: true },
    { id: 'aa_roja_c', label: 'Pista', code: 'ROJA-C', active: true },
    { id: 'aa_naranja_a', label: 'Puente de abordaje', code: 'NARANJA-A', active: true },
    { id: 'aa_naranja_b', label: 'SATE / Hipódromo', code: 'NARANJA-B', active: true },
    { id: 'aa_azul_a', label: 'Aduana', code: 'AZUL-A', active: true },
    { id: 'aa_azul_b', label: 'Migración', code: 'AZUL-B', active: true },
    { id: 'aa_amarilla_a', label: 'Zona internacional', code: 'AMARILLA-A', active: true },
    { id: 'aa_amarilla_b', label: 'Salas de preembarque', code: 'AMARILLA-B', active: true },
    { id: 'aa_blanca_t1', label: 'Terminal 1', code: 'BLANCA-T1', active: true },
    { id: 'aa_blanca_t2', label: 'Terminal 2', code: 'BLANCA-T2', active: true },
    { id: 'aa_celeste_adm', label: 'Administrativo', code: 'CELESTE-ADM', active: true },
  ],
  rejectionReasons: [
    { id: 'rr_1', label: 'Documentación incompleta', code: 'DOC_INCOMPLETO', active: true },
    { id: 'rr_2', label: 'Documento ilegible', code: 'DOC_ILEGIBLE', active: true },
    { id: 'rr_3', label: 'Documento vencido', code: 'DOC_VENCIDO', active: true },
    { id: 'rr_4', label: 'Información inconsistente', code: 'INFO_INCONSISTENTE', active: true },
    { id: 'rr_5', label: 'Firma no autorizada', code: 'FIRMA_NO_AUTH', active: true },
    { id: 'rr_6', label: 'Zona no autorizada', code: 'ZONA_NO_AUTH', active: true },
    { id: 'rr_7', label: 'No cumple requisitos', code: 'NO_REQUISITOS', active: true },
    { id: 'rr_8', label: 'Otro', code: 'OTRO', active: true },
  ],
};
