import type { Company } from '@/lib/types';

export const mockCompanies: Company[] = [
  {
    id: 'co_aac',
    legalName: 'Administración Aeroportuaria Central, S.A.',
    tradeName: 'AAC',
    taxId: 'AAC-155001-2-2015',
    email: 'contacto@aac.aero',
    phone: '+507 275-9000',
    address: 'Edificio Sede, Aeropuerto Internacional, Ciudad',
    primaryContact: 'Roberto Méndez',
    status: 'ACTIVE',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'co_mcd',
    legalName: 'McDonald’s Panamá, S.A.',
    tradeName: 'McDonald’s',
    taxId: 'MCD-778001-1-2018',
    email: 'operaciones@mdpanama.com',
    phone: '+507 269-1100',
    address: 'Local 14, Terminal 1, Aeropuerto Internacional',
    primaryContact: 'Laura Fuentes',
    status: 'ACTIVE',
    createdAt: '2024-02-03T10:00:00Z',
  },
  {
    id: 'co_copa',
    legalName: 'Copa Airlines, S.A.',
    tradeName: 'Copa Airlines',
    taxId: 'CPA-155123-2-2010',
    email: 'accesos@copaair.com',
    phone: '+507 304-2000',
    address: 'Edificio Copa, Hub de las Américas',
    primaryContact: 'Andrés Pino',
    status: 'ACTIVE',
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'co_delta',
    legalName: 'Empresa Contratista Delta, S.A.',
    tradeName: 'Contratista Delta',
    taxId: 'DLT-778456-1-2020',
    email: 'rrhh@deltacontratista.com',
    phone: '+507 321-4400',
    address: 'Galpón 7, Zona Franca, Aeropuerto',
    primaryContact: 'Marta Ríos',
    status: 'ACTIVE',
    createdAt: '2024-03-11T10:00:00Z',
  },
  {
    id: 'co_sap',
    legalName: 'Servicios Aeroportuarios Panamá, S.A.',
    tradeName: 'SAP',
    taxId: 'SAP-155987-2-2012',
    email: 'carnes@sapaero.com',
    phone: '+507 275-7788',
    address: 'Bodega 3, Área de Carga, Aeropuerto',
    primaryContact: 'Carlos Iturra',
    status: 'INACTIVE',
    createdAt: '2024-04-05T10:00:00Z',
  },
];
