import type { Person } from '@/lib/types';

export const mockPeople: Person[] = [
  {
    id: 'pe_001',
    firstName: 'Carlos',
    middleName: 'Eduardo',
    firstLastName: 'Vargas',
    secondLastName: 'López',
    idType: 'CEDULA',
    idNumber: '8-123-456',
    socialSecurityNumber: '12-345-678',
    birthDate: '1988-05-12',
    gender: 'MASCULINO',
    civilStatus: 'CASADO',
    nationality: 'Panameña',
    bloodType: 'O+',
    phone: '+507 275-3300',
    mobile: '+507 6123-4567',
    email: 'c.vargas@copaair.com',
    address: 'Calle 50, Casa 12, Ciudad',
    companyId: 'co_copa',
    department: 'Operaciones',
    position: 'Agente de rampa',
    yearsOfService: 6,
    workedAtAirportBefore: true,
    previousCompany: 'SAP',
    hadPreviousCard: true,
    reusePhoto: true,
    status: 'ACTIVE',
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'pe_002',
    firstName: 'María',
    middleName: 'José',
    firstLastName: 'Fernández',
    secondLastName: 'Quirós',
    marriedLastName: 'de Vargas',
    idType: 'CEDULA',
    idNumber: '4-567-890',
    socialSecurityNumber: '98-765-432',
    birthDate: '1992-11-03',
    gender: 'FEMENINO',
    civilStatus: 'CASADO',
    nationality: 'Panameña',
    bloodType: 'A+',
    phone: '+507 275-3344',
    mobile: '+507 6234-5678',
    email: 'm.fernandez@mdpanama.com',
    address: 'Av. Balboa, PH Bay, Apto 5',
    companyId: 'co_mcd',
    department: 'Operaciones',
    position: 'Supervisora de tienda',
    yearsOfService: 3,
    workedAtAirportBefore: false,
    hadPreviousCard: false,
    reusePhoto: false,
    status: 'ACTIVE',
    createdAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'pe_003',
    firstName: 'Luis',
    middleName: 'Alberto',
    firstLastName: 'Castro',
    secondLastName: 'Mena',
    idType: 'CEDULA',
    idNumber: '3-210-345',
    birthDate: '1990-02-28',
    gender: 'MASCULINO',
    civilStatus: 'SOLTERO',
    nationality: 'Panameña',
    bloodType: 'B+',
    phone: '+507 321-4455',
    mobile: '+507 6345-6789',
    email: 'l.castro@deltacontratista.com',
    address: 'San Francisco, Calle 12',
    companyId: 'co_delta',
    department: 'Mantenimiento',
    position: 'Técnico eléctrico',
    yearsOfService: 4,
    workedAtAirportBefore: true,
    previousCompany: 'AAC',
    hadPreviousCard: true,
    reusePhoto: false,
    status: 'ACTIVE',
    createdAt: '2024-04-10T10:00:00Z',
  },
  {
    id: 'pe_004',
    firstName: 'Ana',
    middleName: 'Lucía',
    firstLastName: 'Pérez',
    secondLastName: 'Solís',
    idType: 'PASAPORTE',
    idNumber: 'PA-1234567',
    birthDate: '1995-07-19',
    gender: 'FEMENINO',
    civilStatus: 'SOLTERO',
    nationality: 'Colombiana',
    bloodType: 'AB+',
    phone: '+507 275-7788',
    mobile: '+507 6456-7890',
    email: 'a.perez@sapaero.com',
    address: 'Costa del Este, Bldg 4',
    companyId: 'co_sap',
    department: 'Carga',
    position: 'Coordinadora de carga',
    yearsOfService: 2,
    workedAtAirportBefore: false,
    hadPreviousCard: false,
    reusePhoto: false,
    status: 'ACTIVE',
    createdAt: '2024-05-01T10:00:00Z',
  },
  {
    id: 'pe_005',
    firstName: 'Jorge',
    middleName: 'Ignacio',
    firstLastName: 'Ramos',
    secondLastName: 'Vidal',
    idType: 'CEDULA',
    idNumber: '6-789-012',
    birthDate: '1985-09-22',
    gender: 'MASCULINO',
    civilStatus: 'CASADO',
    nationality: 'Panameña',
    bloodType: 'O-',
    phone: '+507 304-2010',
    mobile: '+507 6567-8901',
    email: 'j.ramos@copaair.com',
    address: 'Paitilla, Tower Center, Apto 18A',
    companyId: 'co_copa',
    department: 'Seguridad',
    position: 'Analista de seguridad',
    yearsOfService: 9,
    workedAtAirportBefore: true,
    previousCompany: 'Delta',
    hadPreviousCard: true,
    reusePhoto: true,
    status: 'ACTIVE',
    createdAt: '2024-02-25T10:00:00Z',
  },
  {
    id: 'pe_006',
    firstName: 'Elena',
    middleName: 'Rosa',
    firstLastName: 'Soto',
    secondLastName: 'Campos',
    idType: 'CEDULA',
    idNumber: '2-345-678',
    birthDate: '1993-12-08',
    gender: 'FEMENINO',
    civilStatus: 'UNION_LIBRE',
    nationality: 'Panameña',
    bloodType: 'A-',
    phone: '+507 269-1111',
    mobile: '+507 6678-9012',
    email: 'e.soto@mdpanama.com',
    address: 'El Cangrejo, Calle 58',
    companyId: 'co_mcd',
    department: 'Recursos Humanos',
    position: 'Reclutadora',
    yearsOfService: 1,
    workedAtAirportBefore: false,
    hadPreviousCard: false,
    reusePhoto: false,
    status: 'INACTIVE',
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'pe_007',
    firstName: 'Diego',
    middleName: 'Fernando',
    firstLastName: 'Herrera',
    secondLastName: 'Mora',
    idType: 'CEDULA',
    idNumber: '1-901-234',
    birthDate: '1982-03-15',
    gender: 'MASCULINO',
    civilStatus: 'CASADO',
    nationality: 'Panameña',
    bloodType: 'B-',
    phone: '+507 321-4466',
    mobile: '+507 6789-0123',
    email: 'd.herrera@deltacontratista.com',
    address: 'Via Argentina, Casa 22',
    companyId: 'co_delta',
    department: 'Mantenimiento',
    position: 'Jefe de cuadrilla',
    yearsOfService: 7,
    workedAtAirportBefore: true,
    previousCompany: 'AAC',
    hadPreviousCard: true,
    reusePhoto: false,
    status: 'ACTIVE',
    createdAt: '2024-03-28T10:00:00Z',
  },
  {
    id: 'pe_008',
    firstName: 'Sofía',
    middleName: 'Beatriz',
    firstLastName: 'Núñez',
    secondLastName: 'Arias',
    idType: 'CEDULA',
    idNumber: '9-234-567',
    birthDate: '1998-08-30',
    gender: 'FEMENINO',
    civilStatus: 'SOLTERO',
    nationality: 'Panameña',
    bloodType: 'O+',
    phone: '+507 275-9001',
    mobile: '+507 6890-1234',
    email: 's.nunez@aac.aero',
    address: 'San Antonio, Casa 8',
    companyId: 'co_aac',
    department: 'Accesos',
    position: 'Oficial de accesos',
    yearsOfService: 2,
    workedAtAirportBefore: false,
    hadPreviousCard: false,
    reusePhoto: false,
    status: 'ACTIVE',
    createdAt: '2024-06-02T10:00:00Z',
  },
];
