import type { AccessRequest, DocumentItem, RequestHistoryEvent } from '@/lib/types';
import { genId } from '@/lib/constants';

function doc(
  name: string,
  type: string,
  size: number,
  status: 'PENDIENTE' | 'APROBADO' | 'RECHAZADO' = 'APROBADO',
  observation?: string
): DocumentItem {
  return {
    id: genId('doc'),
    name,
    type,
    size,
    uploadedAt: '2026-07-08T10:00:00Z',
    status,
    observation,
  };
}

function ev(
  status: AccessRequest['status'],
  action: string,
  actor: string,
  actorRole: AccessRequest['history'][number]['actorRole'],
  timestamp: string,
  comment?: string
): RequestHistoryEvent {
  return { id: genId('ev'), status, action, actor, actorRole, timestamp, comment };
}

export const mockRequests: AccessRequest[] = [
  {
    id: 'rq_118',
    number: 'SGA-2026-000118',
    type: 'CARNE_PERMANENTE',
    companyId: 'co_copa',
    signerId: 'pe_005',
    reason: 'Renovación de carné permanente para personal de operaciones',
    serviceCompany: '',
    startDate: '2026-08-01',
    endDate: '2027-07-31',
    startTime: '06:00',
    endTime: '22:00',
    observations: 'Personal con experiencia previa en plataforma.',
    personIds: ['pe_001'],
    primaryPersonId: 'pe_001',
    personExtras: {
      pe_001: {
        department: 'Operaciones',
        position: 'Agente de rampa',
        yearsOfService: 6,
        reusePhoto: true,
        emergencyPersonnel: false,
        observations: '',
      },
    },
    vehicles: [],
    tools: [],
    accessPoints: ['Puerta de empleados T1–T2', 'Portón No. 8'],
    zones: [
      { zoneColor: 'ROJA', areaCode: 'A', areaName: 'Plataforma', justification: 'Acceso a plataforma para atención de aeronaves' },
      { zoneColor: 'NARANJA', areaCode: 'A', areaName: 'Puente de abordaje', justification: 'Embarque y desembarque de pasajeros' },
    ],
    documents: [
      doc('cedula_vargas.pdf', 'Cédula o pasaporte', 248_000, 'APROBADO'),
      doc('foto_vargas.jpg', 'Fotografía', 512_000, 'APROBADO'),
      doc('carta_trabajo_copa.pdf', 'Carta de trabajo', 180_000, 'APROBADO'),
      doc('cert_empresa_copa.pdf', 'Certificación de la empresa', 220_000, 'PENDIENTE'),
    ],
    status: 'EN_REVISION_DOCUMENTAL',
    assignedTo: 'us_revisor1',
    createdBy: 'us_andres',
    createdAt: '2026-07-12T14:10:00Z',
    updatedAt: '2026-07-12T14:10:00Z',
    history: [
      ev('ENVIADA', 'Solicitud enviada', 'Andrés Pino', 'ADMIN_EMPRESA', '2026-07-12T14:10:00Z', 'Solicitud creada y enviada'),
      ev('EN_REVISION_DOCUMENTAL', 'Asignada a revisión documental', 'Sistema', 'ADMIN_GENERAL', '2026-07-12T14:11:00Z'),
    ],
  },
  {
    id: 'rq_112',
    number: 'SGA-2026-000112',
    type: 'PERMISO_PERSONA',
    companyId: 'co_mcd',
    signerId: 'pe_002',
    reason: 'Ingreso temporal para auditoría de tienda',
    serviceCompany: 'Auditoría Externa S.A.',
    startDate: '2026-07-20',
    endDate: '2026-07-22',
    startTime: '08:00',
    endTime: '17:00',
    observations: 'Auditoría trimestral.',
    personIds: ['pe_002', 'pe_006'],
    primaryPersonId: 'pe_002',
    vehicles: [],
    tools: [],
    accessPoints: ['Food Court', 'Puerta de empleados T1–T2'],
    zones: [
      { zoneColor: 'BLANCA', areaCode: 'T1', areaName: 'Terminal 1', justification: 'Acceso a locales comerciales' },
    ],
    documents: [
      doc('cedula_fernandez.pdf', 'Cédula o pasaporte', 210_000, 'APROBADO'),
      doc('foto_fernandez.jpg', 'Fotografía', 480_000, 'APROBADO'),
      doc('autorizacion_mcd.pdf', 'Documento de autorización', 160_000, 'APROBADO'),
    ],
    status: 'PENDIENTE_APROBACION',
    assignedTo: 'us_jefe',
    createdBy: 'us_laura',
    createdAt: '2026-07-08T09:00:00Z',
    updatedAt: '2026-07-12T11:30:00Z',
    history: [
      ev('ENVIADA', 'Solicitud enviada', 'Laura Fuentes', 'ADMIN_EMPRESA', '2026-07-08T09:00:00Z'),
      ev('EN_REVISION_DOCUMENTAL', 'Asignada a revisión documental', 'Sistema', 'ADMIN_GENERAL', '2026-07-08T09:05:00Z'),
      ev('DOCUMENTOS_APROBADOS', 'Documentos aprobados', 'Daniela Cruz', 'REVISOR', '2026-07-12T11:30:00Z', 'Documentación completa y legible'),
      ev('PENDIENTE_APROBACION', 'Enviada a aprobación final', 'Daniela Cruz', 'REVISOR', '2026-07-12T11:31:00Z'),
    ],
  },
  {
    id: 'rq_104',
    number: 'SGA-2026-000104',
    type: 'PERMISO_VEHICULO',
    companyId: 'co_delta',
    signerId: 'pe_007',
    reason: 'Ingreso de vehículo para traslado de materiales',
    serviceCompany: '',
    startDate: '2026-07-15',
    endDate: '2026-07-15',
    startTime: '07:00',
    endTime: '16:00',
    observations: '',
    personIds: ['pe_003'],
    primaryPersonId: 'pe_003',
    vehicles: [
      { id: 'vh_1', make: 'Toyota', model: 'Hilux', plate: '8X-23-45', color: 'Blanco', year: 2022, description: 'Pickup de carga' },
    ],
    tools: [],
    accessPoints: ['Portón No. 10', 'Edificio de carga'],
    zones: [
      { zoneColor: 'ROJA', areaCode: 'A', areaName: 'Plataforma', justification: 'Carga en plataforma' },
      { zoneColor: 'VERDE', areaCode: 'A', areaName: 'Plataforma', justification: 'Tránsito de vehículo de carga' },
    ],
    documents: [
      doc('cedula_castro.pdf', 'Cédula o pasaporte', 230_000, 'APROBADO'),
      doc('doc_vehiculo.pdf', 'Documento del vehículo', 195_000, 'RECHAZADO', 'Matrícula vencida'),
      doc('foto_castro.jpg', 'Fotografía', 500_000, 'PENDIENTE'),
    ],
    status: 'DEVUELTA_PARA_CORRECCION',
    assignedTo: undefined,
    createdBy: 'us_marta',
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-11T16:45:00Z',
    history: [
      ev('ENVIADA', 'Solicitud enviada', 'Marta Ríos', 'ADMIN_EMPRESA', '2026-07-05T10:00:00Z'),
      ev('EN_REVISION_DOCUMENTAL', 'Asignada a revisión documental', 'Sistema', 'ADMIN_GENERAL', '2026-07-05T10:05:00Z'),
      ev('DEVUELTA_PARA_CORRECCION', 'Devuelta para corrección', 'Daniela Cruz', 'REVISOR', '2026-07-11T16:45:00Z', 'Matrícula del vehículo vencida. Actualizar documento.'),
    ],
  },
  {
    id: 'rq_099',
    number: 'SGA-2026-000099',
    type: 'CARNE_PERMANENTE',
    companyId: 'co_copa',
    signerId: 'pe_005',
    reason: 'Carné permanente para analista de seguridad',
    serviceCompany: '',
    startDate: '2026-07-01',
    endDate: '2027-06-30',
    startTime: '06:00',
    endTime: '18:00',
    observations: '',
    personIds: ['pe_005'],
    primaryPersonId: 'pe_005',
    personExtras: {
      pe_005: {
        department: 'Seguridad',
        position: 'Analista de seguridad',
        yearsOfService: 9,
        reusePhoto: true,
        emergencyPersonnel: true,
        observations: 'Personal de emergencia',
      },
    },
    vehicles: [],
    tools: [],
    accessPoints: ['Puerta de empleados T1–T2', 'Portón No. 3'],
    zones: [
      { zoneColor: 'ROJA', areaCode: 'B', areaName: 'Calle de rodaje', justification: 'Patrullaje de seguridad' },
      { zoneColor: 'AZUL', areaCode: 'A', areaName: 'Aduana', justification: 'Coordinación con aduana' },
    ],
    documents: [
      doc('cedula_ramos.pdf', 'Cédula o pasaporte', 240_000, 'APROBADO'),
      doc('foto_ramos.jpg', 'Fotografía', 490_000, 'APROBADO'),
      doc('carta_seguridad.pdf', 'Carta de trabajo', 175_000, 'APROBADO'),
      doc('cert_copa.pdf', 'Certificación de la empresa', 210_000, 'APROBADO'),
    ],
    status: 'EN_CONFECCION',
    assignedTo: 'us_emisor',
    createdBy: 'us_andres',
    createdAt: '2026-06-28T11:00:00Z',
    updatedAt: '2026-07-11T08:15:00Z',
    history: [
      ev('ENVIADA', 'Solicitud enviada', 'Andrés Pino', 'ADMIN_EMPRESA', '2026-06-28T11:00:00Z'),
      ev('EN_REVISION_DOCUMENTAL', 'Asignada a revisión documental', 'Sistema', 'ADMIN_GENERAL', '2026-06-28T11:05:00Z'),
      ev('DOCUMENTOS_APROBADOS', 'Documentos aprobados', 'Daniela Cruz', 'REVISOR', '2026-07-01T09:00:00Z'),
      ev('APROBADA', 'Solicitud aprobada', 'Manuel Ortega', 'JEFE_DOCUMENTOS', '2026-07-02T10:00:00Z', 'Cumple todos los requisitos'),
      ev('EN_CONFECCION', 'Confección iniciada', 'Patricia Salas', 'EMISOR_CARNE', '2026-07-11T08:15:00Z'),
    ],
    issuance: { startedAt: '2026-07-11T08:15:00Z' },
  },
  {
    id: 'rq_098',
    number: 'SGA-2026-000098',
    type: 'CARNE_PERMANENTE',
    companyId: 'co_copa',
    signerId: 'pe_005',
    reason: 'Carné permanente para agente de rampa',
    serviceCompany: '',
    startDate: '2026-06-01',
    endDate: '2027-05-31',
    startTime: '06:00',
    endTime: '22:00',
    observations: '',
    personIds: ['pe_001'],
    primaryPersonId: 'pe_001',
    personExtras: {
      pe_001: {
        department: 'Operaciones',
        position: 'Agente de rampa',
        yearsOfService: 5,
        reusePhoto: false,
        emergencyPersonnel: false,
      },
    },
    vehicles: [],
    tools: [],
    accessPoints: ['Puerta de empleados T1–T2', 'Portón No. 8'],
    zones: [
      { zoneColor: 'ROJA', areaCode: 'A', areaName: 'Plataforma', justification: 'Operaciones de rampa' },
    ],
    documents: [
      doc('cedula_vargas.pdf', 'Cédula o pasaporte', 248_000, 'APROBADO'),
      doc('foto_vargas.jpg', 'Fotografía', 512_000, 'APROBADO'),
      doc('carta_copa.pdf', 'Carta de trabajo', 180_000, 'APROBADO'),
    ],
    status: 'ENTREGADA',
    assignedTo: 'us_emisor',
    createdBy: 'us_andres',
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-07-10T10:00:00Z',
    history: [
      ev('ENVIADA', 'Solicitud enviada', 'Andrés Pino', 'ADMIN_EMPRESA', '2026-05-20T10:00:00Z'),
      ev('DOCUMENTOS_APROBADOS', 'Documentos aprobados', 'Daniela Cruz', 'REVISOR', '2026-05-22T09:00:00Z'),
      ev('APROBADA', 'Solicitud aprobada', 'Manuel Ortega', 'JEFE_DOCUMENTOS', '2026-05-23T11:00:00Z'),
      ev('EN_CONFECCION', 'Confección iniciada', 'Patricia Salas', 'EMISOR_CARNE', '2026-07-08T08:00:00Z'),
      ev('LISTA_PARA_ENTREGA', 'Lista para entrega', 'Patricia Salas', 'EMISOR_CARNE', '2026-07-09T10:00:00Z'),
      ev('ENTREGADA', 'Carné entregado', 'Patricia Salas', 'EMISOR_CARNE', '2026-07-10T10:00:00Z', 'Entregado al titular'),
    ],
    issuance: {
      startedAt: '2026-07-08T08:00:00Z',
      readyAt: '2026-07-09T10:00:00Z',
      deliveredAt: '2026-07-10T10:00:00Z',
      receivedBy: 'Carlos Vargas',
      deliveryObservation: 'Entregado al titular en oficina de accesos',
    },
  },
  {
    id: 'rq_095',
    number: 'SGA-2026-000095',
    type: 'PERMISO_HERRAMIENTA',
    companyId: 'co_delta',
    signerId: 'pe_007',
    reason: 'Ingreso de equipos de soldadura',
    serviceCompany: '',
    startDate: '2026-07-18',
    endDate: '2026-07-20',
    startTime: '07:00',
    endTime: '17:00',
    observations: 'Trabajos de reparación en zona de carga.',
    personIds: ['pe_003', 'pe_007'],
    primaryPersonId: 'pe_007',
    vehicles: [],
    tools: [
      { id: 'tl_1', make: 'Lincoln', type: 'Soldadora', serialNumber: 'SN-LIN-001', description: 'Soldadora MIG 250A', quantity: 1 },
      { id: 'tl_2', make: 'Bosch', type: 'Taladro', serialNumber: 'SN-BOS-002', description: 'Taladro de impacto', quantity: 2 },
    ],
    accessPoints: ['Portón No. 10', 'Edificio de carga'],
    zones: [
      { zoneColor: 'VERDE', areaCode: 'A', areaName: 'Plataforma', justification: 'Reparaciones en área de carga' },
    ],
    documents: [
      doc('listado_equipos.pdf', 'Listado de herramientas o equipos', 150_000, 'APROBADO'),
      doc('autorizacion_delta.pdf', 'Documento de autorización', 170_000, 'APROBADO'),
    ],
    status: 'APROBADA',
    assignedTo: 'us_emisor',
    createdBy: 'us_marta',
    createdAt: '2026-07-01T08:00:00Z',
    updatedAt: '2026-07-09T12:00:00Z',
    history: [
      ev('ENVIADA', 'Solicitud enviada', 'Marta Ríos', 'ADMIN_EMPRESA', '2026-07-01T08:00:00Z'),
      ev('DOCUMENTOS_APROBADOS', 'Documentos aprobados', 'Daniela Cruz', 'REVISOR', '2026-07-03T09:00:00Z'),
      ev('APROBADA', 'Solicitud aprobada', 'Manuel Ortega', 'JEFE_DOCUMENTOS', '2026-07-09T12:00:00Z'),
    ],
  },
  {
    id: 'rq_088',
    number: 'SGA-2026-000088',
    type: 'PERMISO_PERSONA',
    companyId: 'co_aac',
    signerId: 'pe_008',
    reason: 'Acceso temporal para inspección de instalaciones',
    serviceCompany: 'Inspecciones Técnicas S.A.',
    startDate: '2026-07-25',
    endDate: '2026-07-26',
    startTime: '09:00',
    endTime: '16:00',
    observations: 'Inspección anual.',
    personIds: ['pe_008'],
    primaryPersonId: 'pe_008',
    vehicles: [],
    tools: [],
    accessPoints: ['Puerta de empleados T1–T2'],
    zones: [
      { zoneColor: 'BLANCA', areaCode: 'T1', areaName: 'Terminal 1', justification: 'Inspección de terminal' },
      { zoneColor: 'CELESTE', areaCode: 'ADM', areaName: 'Administrativo', justification: 'Reunión administrativa' },
    ],
    documents: [
      doc('cedula_nunez.pdf', 'Cédula o pasaporte', 205_000, 'APROBADO'),
      doc('foto_nunez.jpg', 'Fotografía', 470_000, 'APROBADO'),
      doc('autorizacion_aac.pdf', 'Documento de autorización', 155_000, 'APROBADO'),
    ],
    status: 'RECHAZADA',
    assignedTo: undefined,
    createdBy: 'us_admin',
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-06-20T14:00:00Z',
    history: [
      ev('ENVIADA', 'Solicitud enviada', 'Roberto Méndez', 'ADMIN_GENERAL', '2026-06-15T10:00:00Z'),
      ev('EN_REVISION_DOCUMENTAL', 'Asignada a revisión documental', 'Sistema', 'ADMIN_GENERAL', '2026-06-15T10:05:00Z'),
      ev('RECHAZADA', 'Solicitud rechazada', 'Manuel Ortega', 'JEFE_DOCUMENTOS', '2026-06-20T14:00:00Z', 'Zona no autorizada para la empresa solicitante'),
    ],
  },
  {
    id: 'rq_draft_1',
    number: 'SGA-2026-000120',
    type: 'PERMISO_PERSONA',
    companyId: 'co_mcd',
    signerId: 'pe_002',
    reason: 'Ingreso para capacitación de personal',
    serviceCompany: '',
    startDate: '2026-08-05',
    endDate: '2026-08-06',
    startTime: '08:00',
    endTime: '17:00',
    observations: '',
    personIds: ['pe_002'],
    primaryPersonId: 'pe_002',
    vehicles: [],
    tools: [],
    accessPoints: ['Food Court'],
    zones: [],
    documents: [],
    status: 'BORRADOR',
    createdBy: 'us_laura',
    createdAt: '2026-07-12T16:00:00Z',
    updatedAt: '2026-07-12T16:30:00Z',
    history: [
      ev('BORRADOR', 'Borrador creado', 'Laura Fuentes', 'ADMIN_EMPRESA', '2026-07-12T16:00:00Z'),
    ],
  },
];
